---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1vhylxdmlecjncckqcdwapuczy5wtr8euk8ztelus3ammzem0758swdahfe
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1vhylxdmlecjncckqcdwapuczy5wtr8euk8ztelus3ammzem0758swdahfe
