# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: null
    CLOUDFLARE_APIKEY: null
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:L2Ih16g=,iv:FNSq0a2M9nsf8kLqLqhNorsIEm3FU1MlWdgdlyr21Hs=,tag:0aWBA3qYXyj8se4T10xFjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-11T04:53:52Z"
    mac: ENC[AES256_GCM,data:dYC0sbWfVZzTZHMcH9r2FZpMb9w0tRTFLS7YtypzQyj7GN1n/2duHhL6hr7woSnlN0hs8FYpZpr5UysKcowzKtvjyKK4933W7tDE/YYJurEE7UMaM6rlyPgO0RdgWoy7EyttpPgwZ0ImuDZNdwJoK0lmf0EMl+o3C1xhrumX8Zo=,iv:Bp0oU+xr+XY+gE4kxBJ6kdAgERItdkmsaz6K+aNtJ5E=,tag:X3A9kJqaXi98ykIX2UqBxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
