---
kubernetes:
  children:
    master:
      hosts:
        kube-0:
          ansible_host: 10.30.17.40
        kube-1:
          ansible_host: 10.30.17.41
        kube-2:
          ansible_host: 10.30.17.42
