# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: null
    api-key: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-11T04:53:52Z"
    mac: ENC[AES256_GCM,data:wAMhz2xul+HwkTZZTXmsagmE5Av01fGByF6Drm+25pKLNIK0E8x5wzjFJpo4nopLuBnqM2ZNnZzxpHCVWyaV4MMk9Le2BSG9r0YYzVPKfqYXSMg3DAW7UqP1FXkWlZ+adnD16tloTz+kTIjDcvOpRlvNorpFYgvgbwGQmq0Mfg4=,iv:e19zcEc043Q/q2tby5IpgmsqCftM3vCrEUpAGs9rRrc=,tag:TvVl0opgT+fIzz+Fl49hCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
