kind: Secret
ansible_user: ENC[AES256_GCM,data:PGMkOgV6,iv:dh6k/u3eGh5WzIRleetqThNB/Jw9Pdm7ocKdmngX27U=,tag:aAYWqxl2qcjjzmPdsffH1g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:8koLRst4,iv:N9dT2D8fauvY8SQstZ4PbXWPsm1Jgb+/9b5HQ3oihwY=,tag:t5NNleO9g5WcvgrYlbv5gA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vhylxdmlecjncckqcdwapuczy5wtr8euk8ztelus3ammzem0758swdahfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bWlHZjlQRWp3L2NCTTVY
            cjNJOG1XWmFvdFhkRE9NK2FEYlcwQUhLQlN3CitsNDJlTkU0V2s1VTkwYnZHenB0
            MGhKWitLb1FNbzByZWZTbkFNbUdWMmcKLS0tIE5rakZ2OXFHMytycndhNUFwL3Nt
            eDlUdXM2NEtWSTMrZm9kZWlXdFZXREEKQu5Jq3BT+vk6kSXat+8ExkWXD4jGUFYU
            0JC9PLfJfaEaGh3IAr85muAYwReTtOOrHUZWoykD2grqQP24Evv1DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-14T02:05:37Z"
    mac: ENC[AES256_GCM,data:m82WUnvJPFhi5SfUKPEbfUA3FIIUuKPD7tXRaWYUaDuqevtPMukbOWxekrU/2ZeeZ47rwREwjStYaqJoxjY76K5axmll/d7ss6gduAiCBMLrHbXODxI0vbeIzut/iUAQSXRBkGWZarVYOpaIa6iNhkkC64Gq4dUcb1CStiWTA34=,iv:ge4pntmx1nRntYCmA01uUcoiAWPziS/L/hkznjdnaYo=,tag:dT5M7KxWPdE3URzFxHjHwA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
