# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: null
    SECRET_CLOUDFLARE_EMAIL: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-11T04:53:52Z"
    mac: ENC[AES256_GCM,data:7OyNOmYDg+mGnqRB6FVbztzWqsVqbP0bM2EcVGfyExQHMMuInzxB+q3oXk+PUrzPePLAsB9gkTZZK/QQnbv65Udd9AG8FCI4RAbKlFhsAqomOAYZUNk0JJOblNW3PaU3og5CkArbwDZGtiFn5OM6HPp0ipuoAGUQo+c7YZKBtac=,iv:/N6WD33FKkj7khUiMZXu2bPRjZzBfW/mp1AML1JE8o0=,tag:E0C8BSSzYVhqPpyJPmUiwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
