# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:flO07FxfTvvjKg==,iv:GP7WV79XML2PkCABmlrEbSwfS8/rpKoyMm5Kj4QHD2Q=,tag:26RbJ7foPZ3oYrEpR6/5xQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Ccqq3zTOHx/jvFFencfD5A==,iv:HutLIi/ZYC09828GfwlFiFJTUC05kWseED2YLu3S+rQ=,tag:QRSFiWJIuyOdSMbE/p+CGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vhylxdmlecjncckqcdwapuczy5wtr8euk8ztelus3ammzem0758swdahfe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dVdQNVc4RmpidC83T01K
            YjJIZ3ZFU1krWjE2YjF6dVZGWitVK2NTQ1hrCkNlbjA1ZThucFM5eDI5Z0p4ZDkr
            cUF2SStuNVJlOVY1c3BxVWRmWERTc00KLS0tIHJSSEZaRzU5SHBpRG4zZThkcEs1
            OThBaVVLQ3JCcVJPTkI4WW1pQmdCK0kKNJA9n5QlY7ioPl3d1a/i4OqaMixJc0Hx
            OCFvojGSBrX2xheR9zYNiPlRwDHZX43Fn/6p62lttdegQgAhgo9RZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-14T13:06:29Z"
    mac: ENC[AES256_GCM,data:BRNNdnCiKT0qmdO2wEq+1YRGOQAFxK+CtDI3jc93Kcz44kKNl9uBoer+xcoDT6tP/vqSmkN5WNL8qcuBJSwJSOFRdpisak3GU3ZbZnJK/gPmTmn1uBNj95dMtgXKxpHF5T9eXU84oPkicnb6Z6vH63GpN1t4eUvhPAg/FsB428g=,iv:StkAcCTDv8d0CFEaJJtrv1EjFASBr4mLWT5OTOvsrQE=,tag:pCdDvlvXB7Q9p3HpG4gI1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
